<a href="https://colab.research.google.com/github/21pa1a6136/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
x=np.array([1,2,3])
print(x)

[1 2 3]


In [13]:
y=np.array([[1,2,3],[4,5,6]])
print(y)


[[1 2 3]
 [4 5 6]]


In [14]:
import numpy as np
np.arange(10,30,5)

array([10, 15, 20, 25])

In [15]:
b=np.append(x,[4,5,6])
print(b)

[1 2 3 4 5 6]


In [16]:
print("the elements in x before deleting",x)
newarray=np.delete(x,2)
print("The elements in x after deleting",newarray)

the elements in x before deleting [1 2 3]
The elements in x after deleting [1 2]


In [17]:
b=np.array([6,5,4,3,2,1])
b[b<4]=-1
print(b)

[ 6  5  4 -1 -1 -1]


In [23]:
a=np.array([20,30,40,50])
b=np.arange(1,5)
print(a)
print(b)
print("Add",a+b)
print("Sub",a-b)
print("Mult",a*b)
print("Div",a/b)
print("Power of b of 4",b**4)
print("Sin",np.sin(a))
a[0]+=10
print("First number added by 10",a)
print(np.dot(a,b))

[20 30 40 50]
[1 2 3 4]
Add [21 32 43 54]
Sub [19 28 37 46]
Mult [ 20  60 120 200]
Div [20.         15.         13.33333333 12.5       ]
Power of b of 4 [  1  16  81 256]
Sin [ 0.91294525 -0.98803162  0.74511316 -0.26237485]
First number added by 10 [30 30 40 50]
410


In [32]:
a=np.arange(10)**3
print(a)
print(a[3])
print(a[2:4])
print(a[2:3])
print(a[-1])
print(a[-2])
print(a[-5:-2])

[  0   1   8  27  64 125 216 343 512 729]
27
[ 8 27]
[8]
729
512
[125 216 343]


In [44]:
a=np.arange(12).reshape(4,3)**2
print(a)
print(a[1:3])
print(a[1:3,1:2])
print(a[2])
print(a[:3])
print(a[-1])
print(a[-1,-1])

[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]
[[ 9 16 25]
 [36 49 64]]
[[16]
 [49]]
[36 49 64]
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
[ 81 100 121]
121


In [47]:
a=np.arange(12).reshape(4,3)**2
print(a)
print(" ")
for i in a:
  print(i*2)

[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]
 
[0 2 8]
[18 32 50]
[ 72  98 128]
[162 200 242]


In [51]:
a=np.floor(10*np.random.random((3,4)))
print(a)
print(a.reshape(2,6))
print(a.ravel())
print(a.T)

[[7. 9. 5. 8.]
 [6. 7. 5. 9.]
 [9. 5. 6. 4.]]
[[7. 9. 5. 8. 6. 7.]
 [5. 9. 9. 5. 6. 4.]]
[7. 9. 5. 8. 6. 7. 5. 9. 9. 5. 6. 4.]
[[7. 6. 9.]
 [9. 7. 5.]
 [5. 5. 6.]
 [8. 9. 4.]]
